### ISSUE TITLE
[QUESTION]Rackshift开发环境

### ISSUE THREAD

**Issue by isherryforever** [fit2cloud/rackshift#66]
你好，请问Rackshift的开发环境是Linux还是WIndows？使用的编程工具及JDK、Mave版本是否方便告知？在部署时遇到了一些问题想通过单步调试找到原因。

**Comment by yangyy14** [comment]
请问您现在解决了么，我在部署时maven也遇到了一些问题

**Comment by wojiushixiaobai** [comment]
@yangyy14 
- https://github.com/fit2cloud/rackshift/blob/master/.github/workflows/maven.yml
- https://github.com/fit2cloud/rackshift/blob/master/Jenkinsfile

参考这里的构建试试看
